name: szq-helper

on:
  schedule:
    - cron: "18 8 * * *" # 该时间为UTC时间，比北京时间晚8个小时，每天早上7点半自动执行

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run Project
        run: npm install && node index.js ${{secrets.USER}} ${{secrets.PASS}}
