name: szq-helper

on:
  schedule:
    - cron: "00 4 * * *" # 该时间为UTC时间，比北京时间晚8个小时，每天中午12点自动执行

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Send Email
        run: npm install && npm run server
